name: Python package

on:
  pull_request
# on:
#   push:
#     branches:
#       - master

jobs:
  linux-build:
    name: Linux build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install OS dependencies
      run: |
        apt-get update -y
        apt-get install -y python3-dev libgirepository1.0-dev libcairo2-dev libpango1.0-dev libwebkitgtk-3.0-0 gir1.2-webkit-3.0
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/beeware/briefcase.git@v0.3#egg=briefcase
    - name: Build installer
      run: |
        briefcase build

  macOS-build:
    name: macOS build
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/beeware/briefcase.git@v0.3#egg=briefcase
    - name: Build installer
      run: |
        briefcase build macOS dmg

  windows-build:
    name: Windows build
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/beeware/briefcase.git@v0.3#egg=briefcase
    - name: Build installer
      run: |
        briefcase build

  iOS-build:
    name: iOS build
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/beeware/briefcase.git@v0.3#egg=briefcase
    - name: Build installer
      run: |
        briefcase build iOS
